/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.marvel.gateway.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.marvel.gateway.models.*;
import com.marvel.gateway.exceptions.*;
import com.marvel.gateway.APIHelper;
import com.marvel.gateway.Configuration;
import com.marvel.gateway.testing.TestHelper;
import com.marvel.gateway.controllers.ComicsController;

import com.fasterxml.jackson.core.type.TypeReference;

public class ComicsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static ComicsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getComics();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Fetches lists of comics.
     * @throws Throwable
     */
    @Test
    public void testGetComicsCollection() throws Throwable {
        // Parameters for the API call
        String format = "comic";
        FormatTypeEnum formatType = null;
        String noVariants = "true";
        DateDescriptorEnum dateDescriptor = null;
        String dateRange = null;
        String title = null;
        String titleStartsWith = null;
        String startYear = null;
        String issueNumber = null;
        String diamondCode = null;
        String digitalId = null;
        String upc = null;
        String isbn = null;
        String ean = null;
        String issn = null;
        String hasDigitalIssue = "true";
        String modifiedSince = null;
        String creators = null;
        String characters = null;
        String series = null;
        String events = null;
        String stories = null;
        String sharedAppearances = null;
        String collaborators = null;
        String orderBy = "focDate";
        String limit = null;
        String offset = null;

        // Set callback and perform API call
        ComicDataWrapper result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getComicsCollection(format, formatType, noVariants, dateDescriptor, dateRange, title, titleStartsWith, startYear, issueNumber, diamondCode, digitalId, upc, isbn, ean, issn, hasDigitalIssue, modifiedSince, creators, characters, series, events, stories, sharedAppearances, collaborators, orderBy, limit, offset);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
