/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.marvel.gateway.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.marvel.gateway.models.*;
import com.marvel.gateway.exceptions.*;
import com.marvel.gateway.APIHelper;
import com.marvel.gateway.Configuration;
import com.marvel.gateway.testing.TestHelper;
import com.marvel.gateway.controllers.EventsController;

import com.fasterxml.jackson.core.type.TypeReference;

public class EventsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static EventsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getEvents();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Fetches lists of events.
     * @throws Throwable
     */
    @Test
    public void testGetEventsCollection() throws Throwable {
        // Parameters for the API call
        String name = null;
        String nameStartsWith = null;
        String modifiedSince = null;
        String creators = null;
        String characters = null;
        String series = null;
        String comics = null;
        String stories = null;
        String orderBy = "name";
        String limit = null;
        String offset = null;

        // Set callback and perform API call
        EventDataWrapper result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getEventsCollection(name, nameStartsWith, modifiedSince, creators, characters, series, comics, stories, orderBy, limit, offset);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
