/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.marvel.gateway.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.marvel.gateway.models.*;
import com.marvel.gateway.exceptions.*;
import com.marvel.gateway.APIHelper;
import com.marvel.gateway.Configuration;
import com.marvel.gateway.testing.TestHelper;
import com.marvel.gateway.controllers.SeriesController;

import com.fasterxml.jackson.core.type.TypeReference;

public class SeriesControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static SeriesController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getSeries();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Fetches lists of series.
     * @throws Throwable
     */
    @Test
    public void testGetSeriesCollection() throws Throwable {
        // Parameters for the API call
        String title = null;
        String titleStartsWith = null;
        String startYear = null;
        String modifiedSince = null;
        String comics = null;
        String stories = null;
        String events = null;
        String creators = null;
        String characters = null;
        String seriesType = "collection";
        String contains = "comic";
        String orderBy = "title";
        String limit = null;
        String offset = null;

        // Set callback and perform API call
        SeriesDataWrapper result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getSeriesCollection(title, titleStartsWith, startYear, modifiedSince, comics, stories, events, creators, characters, seriesType, contains, orderBy, limit, offset);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
