/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.marvel.gateway.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.marvel.gateway.models.*;
import com.marvel.gateway.exceptions.*;
import com.marvel.gateway.APIHelper;
import com.marvel.gateway.Configuration;
import com.marvel.gateway.testing.TestHelper;
import com.marvel.gateway.controllers.StoriesController;

import com.fasterxml.jackson.core.type.TypeReference;

public class StoriesControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static StoriesController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getStories();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Fetches lists of stories.
     * @throws Throwable
     */
    @Test
    public void testGetStoryCollection() throws Throwable {
        // Parameters for the API call
        String modifiedSince = null;
        String comics = null;
        String series = null;
        String events = null;
        String creators = null;
        String characters = null;
        String orderBy = "id";
        String limit = null;
        String offset = null;

        // Set callback and perform API call
        StoryDataWrapper result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getStoryCollection(modifiedSince, comics, series, events, creators, characters, orderBy, limit, offset);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
