/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.marvel.gateway.models;

import java.util.*;

public class ThumbnailBuilder {
    //the instance to build
    private Thumbnail thumbnail;

    /**
     * Default constructor to initialize the instance
     */
    public ThumbnailBuilder() {
        thumbnail = new Thumbnail();
    }

    public ThumbnailBuilder path(String path) {
        thumbnail.setPath(path);
        return this;
    }

    public ThumbnailBuilder extension(String extension) {
        thumbnail.setExtension(extension);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Thumbnail build() {
        return thumbnail;
    }
}